site_name: jsPsych中文文档
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'green'
    accent: 'orange'
  logo: 'img/jspsych-logo-no-text-mono.svg'
  favicon: 'img/jspsych-favicon.png'
extra_javascript:
  - scripts/convert.js
extra:
  version:
    provider: mike
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Shaobin-Jiang/jsPsych-Chinese-Documentation'
copyright: 'Copyright &copy; 2021 Shaobin Jiang'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
repo_url: 'https://github.com/Shaobin-Jiang/jsPsych-Chinese-Documentation'
repo_name: 'Shaobin-Jiang/jsPsych-Chinese-Documentation'
docs_dir: docs
nav:
- 简介: 'index.md'
- 新手教程:
  - '基础的Hello World': 'tutorials/hello-world.md'
  - '演示实验：简单反应时实验': 'tutorials/rt-task.md'
  - '视频教程': 'tutorials/video-tutorials.md'
- 概述:
  - '创建实验：时间线': 'overview/timeline.md'
  - '插件': 'overview/plugins.md'
  - '动态参数': 'overview/dynamic-parameters.md'
  - '控制呈现样式': 'overview/style.md'
  - '数据存储、汇总和操作': 'overview/data.md'
  - '运行实验': 'overview/running-experiments.md'
  - '实验设置': 'overview/experiment-options.md'
  - '事件相关回调函数': 'overview/callbacks.md'
  - '记录浏览器交互': 'overview/record-browser-interactions.md'
  - '多媒体文件预加载': 'overview/media-preloading.md'
  - '全屏实验': 'overview/fullscreen.md'
  - '眼动': 'overview/eye-tracking.md'
  - '根据浏览器类型排除被试': 'overview/exclude-browser.md'
  - '进度条': 'overview/progress-bar.md'
  - '接入Prolific': 'overview/prolific.md'
  - '接入Mechanical Turk': 'overview/mturk.md'
  - '支持的浏览器和设备': 'overview/browser-device-support.md'
- 参考:
  - 'jsPsych': 'core_library/jspsych-core.md'
  - 'jsPsych.data': 'core_library/jspsych-data.md'
  - 'jsPsych.randomization': 'core_library/jspsych-randomization.md'
  - 'jsPsych.turk': 'core_library/jspsych-turk.md'
  - 'jsPsych.pluginAPI': 'core_library/jspsych-pluginAPI.md'
- 插件:
  - '插件列表': 'plugins/list-of-plugins.md'
  - 'jspsych-animation': 'plugins/jspsych-animation.md'
  - 'jspsych-audio-button-response': 'plugins/jspsych-audio-button-response.md'
  - 'jspsych-audio-keyboard-response': 'plugins/jspsych-audio-keyboard-response.md'
  - 'jspsych-audio-slider-response': 'plugins/jspsych-audio-slider-response.md'
  - 'jspsych-canvas-button-response': 'plugins/jspsych-canvas-button-response.md'
  - 'jspsych-canvas-keyboard-response': 'plugins/jspsych-canvas-keyboard-response.md'
  - 'jspsych-canvas-slider-response': 'plugins/jspsych-canvas-slider-response.md'
  - 'jspsych-call-function': 'plugins/jspsych-call-function.md'
  - 'jspsych-categorize-animation': 'plugins/jspsych-categorize-animation.md'
  - 'jspsych-categorize-html': 'plugins/jspsych-categorize-html.md'
  - 'jspsych-categorize-image': 'plugins/jspsych-categorize-image.md'
  - 'jspsych-cloze' : 'plugins/jspsych-cloze.md'
  - 'jspsych-external-html': 'plugins/jspsych-external-html.md'
  - 'jspsych-free-sort': 'plugins/jspsych-free-sort.md'
  - 'jspsych-fullscreen': 'plugins/jspsych-fullscreen.md'
  - 'jspsych-html-button-response': 'plugins/jspsych-html-button-response.md'
  - 'jspsych-html-keyboard-response': 'plugins/jspsych-html-keyboard-response.md'
  - 'jspsych-html-slider-response': 'plugins/jspsych-html-slider-response.md'
  - 'jspsych-iat-html': 'plugins/jspsych-iat-html.md'
  - 'jspsych-iat-image': 'plugins/jspsych-iat-image.md'
  - 'jspsych-image-button-response': 'plugins/jspsych-image-button-response.md'
  - 'jspsych-image-keyboard-response': 'plugins/jspsych-image-keyboard-response.md'
  - 'jspsych-image-slider-response': 'plugins/jspsych-image-slider-response.md'
  - 'jspsych-instructions': 'plugins/jspsych-instructions.md'
  - 'jspsych-maxdiff': 'plugins/jspsych-maxdiff.md'
  - 'jspsych-preload': 'plugins/jspsych-preload.md'
  - 'jspsych-rdk': 'plugins/jspsych-rdk.md'
  - 'jspsych-reconstruction': 'plugins/jspsych-reconstruction.md'
  - 'jspsych-resize': 'plugins/jspsych-resize.md'
  - 'jspsych-same-different-html': 'plugins/jspsych-same-different-html.md'
  - 'jspsych-same-different-image': 'plugins/jspsych-same-different-image.md'
  - 'jspsych-serial-reaction-time': 'plugins/jspsych-serial-reaction-time.md'
  - 'jspsych-serial-reaction-time-mouse': 'plugins/jspsych-serial-reaction-time-mouse.md'
  - 'jspsych-survey-html-form' : 'plugins/jspsych-survey-html-form.md'
  - 'jspsych-survey-likert': 'plugins/jspsych-survey-likert.md'
  - 'jspsych-survey-multi-choice': 'plugins/jspsych-survey-multi-choice.md'
  - 'jspsych-survey-multi-select': 'plugins/jspsych-survey-multi-select.md'
  - 'jspsych-survey-text': 'plugins/jspsych-survey-text.md'
  - 'jspsych-video-button-response': 'plugins/jspsych-video-button-response.md'
  - 'jspsych-video-keyboard-response': 'plugins/jspsych-video-keyboard-response.md'
  - 'jspsych-video-slider-response': 'plugins/jspsych-video-slider-response.md'
  - 'jspsych-virtual-chinrest' : 'plugins/jspsych-virtual-chinrest.md'
  - 'jspsych-visual-search-circle': 'plugins/jspsych-visual-search-circle.md'
  - 'jspsych-vsl-animate-occlusion': 'plugins/jspsych-vsl-animate-occlusion.md'
  - 'jspsych-vsl-grid-scene': 'plugins/jspsych-vsl-grid-scene.md'
  - 'jspsych-webgazer-calibrate': 'plugins/jspsych-webgazer-calibrate.md'
  - 'jspsych-webgazer-init-camera': 'plugins/jspsych-webgazer-init-camera.md'
  - 'jspsych-webgazer-validate': 'plugins/jspsych-webgazer-validate.md'
- 扩展:
  - '扩展': 'extensions/extensions.md'
  - 'jspsych-ext-webgazer.js': 'extensions/jspsych-ext-webgazer.md'
- 关于:
  - '关于jsPsych': 'about/about.md'
  - '寻求帮助': 'about/support.md'
  - '贡献代码': 'about/contributing.md'
  - '许可证': 'about/license.md'
